name: deploy-terraform
on: 
  pull_request:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
    secrets:
      aws-role-arn:
        required: true
  # workflow_dispatch:

permissions:
      id-token: write
      contents: read    

defaults:
  run:
    working-directory: ./infra/aws/      

jobs:
  check-tf-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Assert TF vars present
        shell: bash
        env:
          TF_VAR_route53_zone_id:           ${{ secrets.ROUTE53_ZONE_ID }}
          TF_VAR_cloudfront_zone_id:        ${{ secrets.CLOUDFRONT_ZONE_ID }}
          TF_VAR_aws_cloudfront_distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          TF_VAR_acm_certificate_arn:       ${{ secrets.ACM_CERT_ARN }}
          TF_VAR_bucket_name:               ${{ secrets.BUCKET_NAME }}
          TF_VAR_ecr_repo:                  ${{ secrets.ECR_REPO }}
          TF_VAR_kms_key_arn:               ${{ secrets.KMS_KEY_ARN }}
        run: |
          for v in \
            TF_VAR_route53_zone_id \
            TF_VAR_cloudfront_zone_id \
            TF_VAR_aws_cloudfront_distribution \
            TF_VAR_acm_certificate_arn \
            TF_VAR_bucket_name \
            TF_VAR_ecr_repo \
            TF_VAR_kms_key_arn
          do
            if [ -z "${!v}" ]; then
              echo "❌ Missing $v"; exit 1
            else
              echo "::add-mask::${!v}"
              echo "✅ $v present"
            fi
          done

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.aws-role-arn}}
          aws-region: ${{inputs.aws-region}}

      - name: Download Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform fmt
        id: fmt
        run: terraform fmt 

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_acm_certificate_arn: ${{secrets.ACM_CERT_ARN}}
          TF_VAR_cloudfront_zone_id: ${{secrets.CLOUDFRONT_ZONE_ID}}
          TF_VAR_aws_cloudfront_distribution: ${{secrets.CLOUDFRONT_DISTRIBUTION}}
          TF_VAR_ecr_repo_name: ${{secrets.ECR_REPO}}
          TF_VAR_kms_key_arn: ${{secrets.KMS_KEY_ARN}}
          TF_VAR_route53_zone_id: ${{secrets.ROUTE53_ZONE_ID}}
          TF_VAR_s3_bucket: ${{secrets.S3_BUCKET}}
        id: plan
        run: terraform plan -out=tfplan -input=false